//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tarifX.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class FoodFromPeople
    {
        public int ID { get; set; }
        public string PublishedBy { get; set; }
        public string Title { get; set; }
        [AllowHtml]
        public string Content { get; set; }
        [AllowHtml]
        public string Materials { get; set; }
        public Nullable<int> NumberOfPeople { get; set; }
        public Nullable<int> PreparationTime { get; set; }
        public Nullable<int> CookingTime { get; set; }
        public Nullable<System.DateTime> PublishingDate { get; set; }
        public string Photo { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
