//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tarifX.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tarifXEntities1 : DbContext
    {
        public tarifXEntities1()
            : base("name=tarifXEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<FoodFromPeople> FoodFromPeoples { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
